### ISSUE TITLE
Hash and message doesn’t  match after solving the generated instance

### ISSUE THREAD

**Issue by ImposterMido** [vsklad/cgen#5]
First of all sorry of inconvenience and hope you could help me I have encoded a sha256 instance with no M or H assigned then solved it , i took the 1st 512 variables (M) then convert it to binary by taking true variables as 1 and false as 0 then used the 512 bits as input for an online sha256 then took the resultant output in hex and converted it to binary and when i compared it to the variables contribute to H it doesn't match although it must match as the message is fixed , also i tried to convert message into text or hex but both give hash doesn't match the real hash any ideas to solve this problem ?

**Comment by ImposterMido** [comment]
Is this due to an error i have done during the getting M and H or is there a certain way to get the message and hash that accurately match the normal sha256 encoding ?

**Comment by vsklad** [comment]
please kindly provide the message and the hash value, I will look into it
it is supposed to match of course
also, when assigning or interpreting variables please note the ordering is big endian

**Comment by ImposterMido** [comment]
Hello sir t i have solved the instance by cryptominisat and collected the
message and has from variables then tried to compute it , i would send text
file contain the instance and the solution file to check and also tell me
if i am doing something wrong and show me accurate steps !

**Comment by ImposterMido** [comment]
sorry for being late here are the instance without m or h assigned and the
solution generated by cryptominisat could you double check please and tell
me if i am wrong and if so show the exact steps to achieve reliable results
as you would generate

**Comment by vsklad** [comment]
please note there is no attachment with the last message
please kindly attach/specify:
1) the instance itself that you are trying to solve
2) the intended message/hash values
3) the bits of the instance (message/hash) that you are trying to assign before solving
4) the solution produced by the solver

**Comment by ImposterMido** [comment]
Kindly double check as it appears to me that zipped folder named instance
and solution is already sent , the instance is without hash or message
assigned , the solution contains variables values , when trying to get the
first 512 bits (M) and convert it to hex then apply sha256 from external
source , the variables contribute to hash in the solution file doesnt match
with it !

**Comment by ImposterMido** [comment]
I have sent it again to make sure it reaches you !

**Comment by ImposterMido** [comment]
Just in case it doesnt reach you could you please explain to me exactly in
details how to convert the bits of message and hash from the solution of
the instance in terms of conversion till reach the text represent message
and hash !

**Comment by ImposterMido** [comment]
Hello sir , i have tried what you said exactly create an instance with 512
bits message and used padding and havent encoded any M or H and tried to
solved it , it seems harder but when solved i tried to convert message bits
into hash using sha256 tool then when comparing binary bits of H in the
solution of instance with the hash already got from sha256 tool based on
the M bits it didnt also match i want to know where does the problem lie in
? Could you please help me i will send the problem and its solution so you
could do your steps yo check if i am right or i am doing something wrong so
you tell me the exact steps to get them match !
