### ISSUE TITLE
I faced the issue of non match of message and hash 

### ISSUE THREAD

**Issue by Htkon** [vsklad/cgen#6]
I have faced the same problem impostermido posted so the message and hash when computed as sat instance solved by cryptominisat it doesnt match seems that many people need to know how to be solved need yoyr help !

**Comment by vsklad** [comment]
please kindly provide the message and the hash value, I will look into it

**Comment by Htkon** [comment]
Sorry for being late i am just watching the updates in impostermido’s issue
as it is close to mine so not disturb you waiting for you to completely
solve his issue and give steps for ideal recover of message and hash so in
turn i got my issue solved !

بتاريخ الاثنين، 9 أكتوبر 2023، جاء من vsklad ***@***.***>:

**Comment by vsklad** [comment]
Ok. Without a meaningful example it is not possible to fully understand or reproduce the steps you re trying to do.
Here is a test which produces correct results:

1. Produce a CNF template without any parameters assigned
    1. ./cgen encode sha256
    2. Output file: sha256r64.cnf
2. Take hex 1234 as a message, assign it to the instance and evaluate it:
    1. ./cgen process sha256r64.cnf -vM 0x1234 pad:sha1 sha256_1234.cnf
    2. M = {0x12348000, 0x00000000/14, 0x00000010}
    3. Output file: sha256_1234.cnf
    4. The formula is SATISFIABLE with 1 solution
    5. Open sha256_1234.cnf, in it
        1. c var H = {0x3a103a4e, 0x5729ad68, 0xc02a678a, 0xe39accfb, 0xc0ae2080, 0x96437401, 0xb7ceab63, 0xcca0622f}
3. Go to https://emn178.github.io/online-tools/sha256.html, calculate hash for the same message, compare the result
    1. Choose “hex” as input type and type “1234” as input
    2. The hash is: 3a103a4e5729ad68c02a678ae39accfbc0ae208096437401b7ceab63cca0622f
As you can see the hash value is the same, there is no issue.

If you find a message which produces incorrect hash, please send me the message I will have a look.
Or, please describe exactly what you are trying to do, with the values of the message and the hash in question, and I can try to reproduce also.

**Comment by Htkon** [comment]
I get in touch with imposter mido and i was looking forward to check for
research purpose if assigning hash to instance and solve it ( if its
solvable in reliable time) could give pre image for hash and if it will
give all potential messages for hash but he doesnt have answer for that if
you could help !

بتاريخ الأحد، 15 أكتوبر 2023، جاء من vsklad ***@***.***>:
